# Generated by Django 4.2.7 on 2023-11-26 05:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category_app', '0001_initial'),
        ('brand_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField()),
                ('price', models.PositiveIntegerField()),
                ('release_at', models.DateField()),
                ('sale', models.BooleanField(default=False)),
                ('brand_name', models.ForeignKey(default='unknown', on_delete=django.db.models.deletion.SET_DEFAULT, to='brand_app.brand')),
                ('genre', models.ManyToManyField(to='category_app.category')),
            ],
        ),
    ]
