# Generated by Django 4.2.7 on 2023-12-17 11:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events_app', '0001_initial'),
        ('game_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='sale',
        ),
        migrations.AddField(
            model_name='game',
            name='event',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, to='events_app.event'),
        ),
    ]
