# Generated by Django 4.2.7 on 2023-12-17 11:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events_app', '0001_initial'),
        ('game_app', '0002_remove_game_sale_game_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='event',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='events_app.event'),
        ),
    ]
