# Generated by Django 4.2.7 on 2023-12-18 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_app', '0003_alter_game_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='is_free',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='release_at',
            field=models.DateField(blank=True, null=True),
        ),
    ]
