# Generated by Django 4.2.7 on 2023-12-17 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0002_alter_customuser_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='number_of_purchases',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
