# Generated by Django 4.2.7 on 2023-12-18 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0003_customuser_number_of_purchases'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='history_of_purchases',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
