# Generated by Django 4.2.7 on 2023-12-18 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_app', '0003_alter_game_event'),
        ('user_app', '0004_customuser_history_of_purchases'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='history_of_purchases',
        ),
        migrations.AddField(
            model_name='customuser',
            name='history_of_purchases',
            field=models.ManyToManyField(blank=True, default=0, null=True, to='game_app.game'),
        ),
    ]
